// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNmiTXjt9dAqWrBqyxoIZTdPQsYLEy-jk',
    appId: '1:713104540090:web:1a17029ca29f07041d1d83',
    messagingSenderId: '713104540090',
    projectId: 'floodauth',
    authDomain: 'floodauth.firebaseapp.com',
    storageBucket: 'floodauth.appspot.com',
    measurementId: 'G-06EJB5XJST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF24FmX2VPDLsqJsPlzhAZN5raK5E294g',
    appId: '1:713104540090:android:22cd13cc76a3ffba1d1d83',
    messagingSenderId: '713104540090',
    projectId: 'floodauth',
    storageBucket: 'floodauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMUkLqW6wCiw901ZhTieJoRrWKKbkenw',
    appId: '1:713104540090:ios:31ef3489aab682481d1d83',
    messagingSenderId: '713104540090',
    projectId: 'floodauth',
    storageBucket: 'floodauth.appspot.com',
    iosClientId: '713104540090-od6l3d97t2jkgg98poala4l4bv7q9p9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.floodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIMUkLqW6wCiw901ZhTieJoRrWKKbkenw',
    appId: '1:713104540090:ios:7abf35d171c825021d1d83',
    messagingSenderId: '713104540090',
    projectId: 'floodauth',
    storageBucket: 'floodauth.appspot.com',
    iosClientId: '713104540090-i5i5o7fdalgqi3vaq0jm62phrjgqap7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.floodApp.RunnerTests',
  );
}
